spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: compras-api
      username: root
      password: root
      authenticationDatabase: admin
  jackson:
    default-property-inclusion: NON_NULL
jwt:
  secret: bec0a820-7904-4c56-bb0f-47ed8e9703ed
  expiration: 36000000
#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

third-party:
  external-api-url: http://localhost:8086/v1/cashback
  token: ZXPURQOARHiMc6Y0flhRC1LVlZQVFRnm

cashback:
  criteria:
    -
      name: Purchases up to 1000
      valueAbove: 0
      cashbackPercent: 0.10
    -
      name: Purchases between 1000 and 1500
      valueAbove: 1000
      cashbackPercent: 0.15
    -
      name: Purchases above 1500
      valueabove: 1500
      cashbackPercent: 0.20

  logstash:
    host: localhost
    port: 5000
