spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: compras-api
      username: root
      password: root
      authenticationDatabase: admin
  security:
    user:
      name: user
      password: 123
  jackson:
    default-property-inclusion: NON_NULL
jwt:
  secret: bec0a820-7904-4c56-bb0f-47ed8e9703ed
  expiration: 360000